# Generated by Django 2.2 on 2022-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='Phone_number',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
