# Generated by Django 2.2 on 2022-05-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='reoder_level',
            new_name='reorder_level',
        ),
    ]
