# Generated by Django 2.2 on 2022-05-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_auto_20220506_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Accaracides', 'Accaracides'), ('Injectibles', 'Injectibles'), ('Salts', 'Salts'), ('Dewormers', 'Dewormers'), ('Levamisoles', 'Levamisoles'), ('Seeds', 'Seeds')], max_length=50, null=True),
        ),
    ]
