# Generated by Django 2.2 on 2022-05-11 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_auto_20220508_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='datefield',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
