# Generated by Django 2.2 on 2022-05-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0006_stock_reoder_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='datefield',
            new_name='timestamp',
        ),
    ]
