# Generated by Django 2.2 on 2022-05-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0007_auto_20220511_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='received_from',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
